version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres-python
      - PG_PORT=5432
      - PG_HOST=db-python
    depends_on:
      - db-python

  db-python:
    container_name: db-python
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres-python
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}