# Generated by Django 3.2.5 on 2023-12-23 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
